name = "SpecialFxns"
uuid = "b2636ea5-33c8-40c0-99e8-0b7ea2db03ca"
authors = ["Ian-Harreschou <harresci@oregonstate.edu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
